# Generated by Django 3.2 on 2023-01-12 04:57

from django.db import migrations, models
import src.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to=src.user.models.upload_path_user, validators=[src.user.models.validate_image]),
        ),
    ]
